### ISSUE TITLE
Strange BIDI levels on RTL text

### ISSUE THREAD

**Issue by kotuk81** [fribidi/fribidi#18]
I'm running the code below: 

FriBidiChar*     unicodeString = new FriBidiChar[textLength];
FriBidiCharType* bidiTypes     = new FriBidiCharType[textLength];
FriBidiLevel*    bidiLevels    = new FriBidiLevel[textLength];

std::string text = "some.\ncar.\nhere.";

// Convert string to unicode
FriBidiStrIndex  len = fribidi_charset_to_unicode(FRIBIDI_CHAR_SET_UTF8, text.c_str(), (FriBidiStrIndex)text.length(), unicodeString);

// Get BIDI types
fribidi_get_bidi_types(unicodeString, (uint32_t)text.size(), bidiTypes);

// Get BIDI levels
FriBidiLevel   resolveParDir = fribidi_get_par_embedding_levels(bidiTypes, (uint32_t)text.size(), FRIBIDI_PAR_RTL, bidiLevels);

And in the result, I get the BIDI levels below: 
2 2 2 2 1 1 0 0 0 0 1 0 0 0 0 0 

The question is:  why I have a level change for the first '.'?

![image](https://user-images.githubusercontent.com/31093884/30019355-f1b16dc0-9168-11e7-8c81-44e23e1897f7.png)

**Comment by dov** [comment]
This is according to the spec. Since the baselevel is 1, the LTR characters get bumped to level 2, since the unicode algorithm always increases the bidi level, but when you reach the neutral character the level returns down to . The different behavior on lines 2 and 3 is irrelevant, as the the external direction FRIBIDI_PAR_RTL on catches for the first line (paragraph). `fribidi_get_par_embedding_levels()` is not really built for handling multiple paragraphs, and you should really call i one paragraph (line) at a time.
