### ISSUE TITLE
wrong direction

### ISSUE THREAD

**Issue by Ram3zani** [fribidi/fribidi#42]
Hello everyone I have question about ffmpeg when it make hardsub. my native language is farsi. i have subtite which in a line have mixed english and farsi word. when i make hardsub. subtitle have issue. in line have mixed english and farsi word direction is wrong. for example first screenshot is correct line in libreoffice writer and secend screenshot is output ffmpeg with wrong direction. is that fribidi bug?
![correct-direction](https://user-images.githubusercontent.com/17659342/35507370-c01401bc-0501-11e8-8abf-c9d1498c36d9.jpg)
![wrong-direction](https://user-images.githubusercontent.com/17659342/35507377-c4944cd8-0501-11e8-9814-8e7e1979394d.jpg)

**Comment by dov** [comment]
This is not a bug in fribidi, but just wrong usage from ffmpeg. In order to get the right display, the usage application must set the base direction. This may either be hard set, e.g. as a property of the subtitle file, or be determined heuristically from the text contents, e.g. by the first "hard" character in the text, or by the direction of most of the characters. See the unicode specification for details: http://unicode.org/reports/tr9/ . You should open a bug report/feature request of ffmpeg.
